[package]
name = "git-branch-picker"
version = "0.1.0"
authors = ["David Pedersen <david.pdrsn@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.69"
chrono = "0.4.23"
git2 = { version = "0.16.1", default_features = false }
skim = "0.10.2"
